Update deploy

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -19,44 +19,90 @@
 # ----- START EDITING HERE -----
 
 # The slug of your WordPress.org plugin
-WP_PLUGIN_SLUG="__CHANGE_THIS__"
+# You need publish your plugin first: https://wordpress.org/plugins/developers/add/
+WP_PLUGIN_SLUG="your_plugin_slug"
 
-# GITHUB user who owns the repo
-GITHUB_REPO_SLUG="__CHANGE_THIS__"
+# The GITHUB repository
+# format: username/repository (example: luizbills/wp-tweaks) 
+GITHUB_REPO_SLUG="your_gh_username/your_gh_repo" 
 
-# folder with plugin icon, banner and screenshots used in https://wordpress.org
-PLUGIN_ASSETS_DIR=".wp-org"
+# The main Github repository branch
+MAIN_BRANCH="master";
+
+# directory with plugin icon, banner and screenshots used in https://wordpress.org
+PLUGIN_ASSETS_DIR=".wordpress-org"
 
 # ----- STOP EDITING HERE -----
+
+# Parse cli arguments
+ONLY_TRUNK="no"
+POSITIONAL_ARGS=()
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    --only-trunk)
+      ONLY_TRUNK="yes"
+      shift
+      ;;
+    -*|--*)
+      echo "Unknown option $1"
+      exit 1
+      ;;
+	*)
+      POSITIONAL_ARGS+=("$1") # save positional arg
+      shift # past argument
+      ;;
+  esac
+done
+set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
 
 set -e
 clear >$( tty ) # clear the terminal
 
-# ASK INFO
 echo "--------------------------------------------"
 echo "      Github to WordPress.org RELEASER      "
 echo "--------------------------------------------"
-read -p "RELEASE VERSION: " VERSION
-echo "--------------------------------------------"
-echo ""
-echo "Before continuing, confirm that you have done the following :)"
-echo ""
-read -p " - Added a changelog for "${VERSION}"?"
-read -p " - Set version in the readme.txt and main file to "${VERSION}"?"
-read -p " - Set stable tag in the readme.txt file to "${VERSION}"?"
-read -p " - Updated the POT file?"
-read -p " - Committed all changes up to GITHUB?"
-echo ""
-read -p "PRESS [ENTER] TO BEGIN RELEASING "${VERSION}
-clear
 
-# VARS
+if [ "$ONLY_TRUNK" == "yes" ];
+then
+	read -p "PRESS [ENTER] TO BEGIN UPDATING THE \"trunk\""
+else
+	REMOTE_README_TXT="https://raw.githubusercontent.com/${GITHUB_REPO_SLUG}/${MAIN_BRANCH}/readme.txt"
+	STABLE_TAG=$( curl -m 3 -s $REMOTE_README_TXT | sed -n 's/Stable tag: \([0-9]\.[0-9]\.[0-9]*\).*/\1/p' )
+
+	trim_spaces() {
+		# Usage: trim_spaces "   example   string    "
+		: "${1#"${1%%[![:space:]]*}"}"
+		: "${_%"${_##*[![:space:]]}"}"
+		printf '%s\n' "$_"
+	}
+	STABLE_TAG=$( trim_spaces $STABLE_TAG )
+
+	# ASK INFO
+	read -p "RELEASE VERSION$( [ $STABLE_TAG ] && echo " [$STABLE_TAG]" || echo "" ): " VERSION
+
+	VERSION=${VERSION:-$STABLE_TAG}
+
+	echo "--------------------------------------------"
+	echo ""
+	echo "Before continuing, confirm that you have done the following ..."
+	echo ""
+	read -p " - Added a changelog for "${VERSION}"?"
+	read -p " - Set version in the main file to "${VERSION}"?"
+	read -p " - Set stable tag in the readme.txt file to "${VERSION}"?"
+	read -p " - Updated the POT file?"
+	read -p " - Committed all changes up to GITHUB?"
+	echo ""
+	read -p "PRESS [ENTER] TO BEGIN RELEASING "${VERSION}
+
+	clear >$( tty ) # clear the terminal
+fi
+
+SVN_REPO="http://plugins.svn.wordpress.org/${WP_PLUGIN_SLUG}/"
+GIT_REPO="https://github.com/${GITHUB_REPO_SLUG}.git"
 CURRENT_DIR="."
 DIR="$( realpath ${CURRENT_DIR} )"
 TEMP_GITHUB_REPO="/tmp/${WP_PLUGIN_SLUG}-git"
 TEMP_SVN_REPO="/tmp/${WP_PLUGIN_SLUG}-svn"
-SVN_REPO="http://plugins.svn.wordpress.org/${WP_PLUGIN_SLUG}/"
-GIT_REPO="https://github.com/${GITHUB_REPO_SLUG}.git"
 
 # DELETE OLD TEMP DIRS
 rm -Rf $TEMP_GITHUB_REPO
@@ -69,8 +115,9 @@ git clone --progress --recurse-submodules $GIT_REPO $TEMP_GITHUB_REPO || { echo 
 # MOVE INTO GIT DIR
 cd "$TEMP_GITHUB_REPO"
 
+clear >$( tty ) # clear the terminal
+
 # LIST BRANCHES
-# clear
 git fetch origin
 echo "WHICH BRANCH DO YOU WISH TO DEPLOY?"
 git branch -r || { echo "Unable to list branches."; exit 1; }
@@ -92,6 +139,18 @@ then
 	echo "Installing composer packages"
 	npm install || { echo "Unable to install npm packages."; exit 1; }
 fi
+
+echo "Looking for PHP syntax errors"
+find . -type f -name '*.php' ! -path './vendor/*' -print0 | while read -d $'\0' file
+do
+	output=$(php -l "$file")
+	if [ ! $? -eq 0 ];
+	then
+		echo -e "\e[31mPHP Syntax Error!\e[0m"
+		exit 1
+	fi
+done
+echo "No syntax errors found"
 
 # REMOVE UNWANTED FILES & FOLDERS
 echo "Removing unwanted files"
@@ -115,9 +174,12 @@ rm -f .editorconfig
 rm -f CONTRIBUTING.md
 rm -f .gitpod.dockerfile
 rm -f .gitpod.yml
+rm -f .prettierrc.json
 
 echo ""
 read -p "PRESS [ENTER] TO DEPLOY BRANCH "${BRANCH}
+
+clear >$( tty ) # clear the terminal
 
 # CHECKOUT SVN DIR IF NOT EXISTS
 echo "Checking out WordPress.org plugin SVN repository"
@@ -130,9 +192,6 @@ cd "$TEMP_SVN_REPO"
 echo "Updating SVN"
 svn update || { echo "Unable to update SVN."; exit 1; }
 
-echo "Checking Plugin icon, banner and screenshots ..."
-rm -Rf assets/
-
 # DELETE TRUNK
 echo "Replacing trunk"
 rm -Rf trunk/
@@ -140,10 +199,18 @@ rm -Rf trunk/
 # COPY GIT DIR TO TRUNK
 cp -a "${TEMP_GITHUB_REPO}/." trunk/
 
-mv trunk/$PLUGIN_ASSETS_DIR assets
+if [[ -d "trunk/${PLUGIN_ASSETS_DIR}" ]];
+then
+	echo "Checking Plugin icon, banner and screenshots ..."
+	rm -Rf assets/
+	mv trunk/$PLUGIN_ASSETS_DIR assets
+fi
 
-# DELETE VERSION TAG
-rm -Rf tags/${VERSION}
+if [ "$ONLY_TRUNK" == "no" ];
+then
+	# DELETE VERSION TAG
+	rm -Rf tags/${VERSION}
+fi
 
 # DO THE ADD ALL NOT KNOWN FILES UNIX COMMAND
 svn add --force * --auto-props --parents --depth infinity -q
@@ -157,29 +224,47 @@ do
     svn rm --force "$MISSING_PATH"
 done
 
-# COPY TRUNK TO TAGS/$VERSION
-echo "Copying trunk to new tag"
-svn copy trunk tags/${VERSION} || { echo "Unable to create tag."; exit 1; }
+if [ "$ONLY_TRUNK" == "no" ];
+then
+	# COPY TRUNK TO TAGS/$VERSION
+	echo "Copying trunk to new tag"
+	svn copy trunk tags/${VERSION} || { echo "Unable to create tag."; exit 1; }
+fi
+
+clear >$( tty ) # clear the terminal
 
 # DO SVN COMMIT
-# clear
 echo "Showing SVN status"
 svn status
 
 # PROMPT USER
 echo ""
-read -p "PRESS [ENTER] TO COMMIT RELEASE "${VERSION}" TO WORDPRESS.ORG"
+if [ "$ONLY_TRUNK" == "no" ];
+then
+	read -p "PRESS [ENTER] TO COMMIT RELEASE "${VERSION}" TO WORDPRESS.ORG"
+else
+	read -p "PRESS [ENTER] TO UPDATE THE \"trunk\" ON WORDPRESS.ORG"
+fi
 echo ""
+clear >$( tty ) # clear the terminal
 
 # DEPLOY
 echo ""
 echo "Committing to WordPress.org...this may take a while..."
-svn commit -m "Release "${VERSION}", see readme.txt for the changelog." || { echo "Unable to commit."; exit 1; }
+
+if [ "$ONLY_TRUNK" == "no" ];
+then
+	COMMIT_MESSAGE="Release "${VERSION}", see readme.txt for the changelog."
+else
+	COMMIT_MESSAGE="Update trunk."
+fi
+
+svn commit -m "$COMMIT_MESSAGE" || { echo "Unable to commit."; exit 1; }
 
 # REMOVE THE TEMP DIRS
-echo "CLEANING UP"
+echo "CLEANING UP ..."
 rm -Rf "$TEMP_GITHUB_REPO"
 rm -Rf "$TEMP_SVN_REPO"
 
 # DONE, BYE
-echo "RELEASER DONE :D"
+echo "RELEASER DONE!"
